<a href="https://colab.research.google.com/github/SARA3SAEED/LLM-2/blob/main/15Faiss_Indexing_Entire_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install datasets nltk
from datasets import load_dataset
import nltk
nltk.download('punkt')
from nltk.tokenize import sent_tokenize



text_dataset =  load_dataset("SaiedAlshahrani/Arabic_Wikipedia_20230101_bots")

text = text_dataset['train']['text']

sentences = []
for item in text:
    sentences.extend(sent_tokenize(item))

documents = sentences[:1000000]
print(len(documents))
print(documents[0])

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 547.8/547.8 kB 10.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 4.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 316.1/316.1 kB 18.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.9/39.9 MB 13.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 1.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 4.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 9.2 MB/s eta 0:00:00
  Attempting uninstall: requests
    Found existing installation: requests 2.31.0
    Uninstalling requests-2.31.0:
      Successfully uninstalled requests-2.31.0
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 14.0.2
    Uninstalling pyarrow-14.0.2:
      Successfully uninstalled pyarrow-14.0.2
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2024.6.1
    Uninstalling fsspec-2024.6.1:
     

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


Generating train split:   0%|          | 0/1087947 [00:00<?, ? examples/s]

1000000
text


In [ ]:
len(set(documents))
sentences = [word for word in list(set(documents)) if type(word) is str]


In [ ]:
len(sentences)

980245

In [ ]:
sentences = sentences[:500000]


In [ ]:
len(sentences)

500000

In [ ]:
import numpy as np
!pip install faiss-gpu

In [ ]:
!pip install -U sentence-transformers

In [ ]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer("sentence-transformers/all-mpnet-base-v2")

In [ ]:
%%time
sentence_embeddings = model.encode(sentences)
sentence_embeddings.shape

CPU times: user 3h 4min 39s, sys: 23.1 s, total: 3h 5min 2s
Wall time: 2h 55min 43s


(500000, 768)

In [ ]:
sentences[1]

'إيمي هيكرلينج هي كات بة وكاتبة سيناريو ومنتجة أفلام ومخرجة وممثلة أمريكية ولدت في مايو بذا برونكس في الولايات المتحدة أعمال أفلام فاست تايمز آت ريدجمونت مراجع وصلات خارجية تصنيف منتجات تلفزيون أمريكيات تصنيف أشخاص من البرونكس تصنيف خريجو مدرسة تيش العليا للفنون تصنيف خريجو معهد الكونسرفتوار تصنيف كاتبات تلفاز أمريكيات تصنيف كاتبات سيناريو أمريكيات تصنيف كتاب أمريكيون يهود تصنيف كتاب تلفاز أمريكيون تصنيف كتاب سيناريو من ولاية نيويورك تصنيف مخرجات أفلام أمريكيات تصنيف مخرجات تلفزيون تصنيف مخرجو أفلام كوميدية تصنيف مخرجو أفلام من مدينة نيويورك تصنيف مخرجو تلفزيون أمريكيون تصنيف منتجات أفلام أمريكيات تصنيف منتجات تلفزيون تصنيف منتجو أفلام أمريكيون تصنيف منتجو تلفزيون من مدينة نيويورك تصنيف مواليد تصنيف خريجو المدارس الثانوية في الفن وتصميم تصنيف مخرجات تلفزيون أمريكيات'

In [ ]:
sentence_embeddings[1]

array([ 9.76093020e-03,  5.80193065e-02, -9.09396261e-03,  1.32582849e-02,
       -5.56323491e-02,  3.29734525e-03,  7.65440241e-02,  1.78928431e-02,
        4.48819101e-02,  1.54563077e-02,  2.36134846e-02, -1.91186871e-02,
        1.42873069e-02, -4.31122072e-02, -2.32334295e-03,  4.46159542e-02,
       -2.64614401e-03,  1.29004624e-02, -2.15329062e-02,  5.20916991e-02,
       -3.92509028e-02,  4.89964560e-02,  3.70187499e-03, -4.79738083e-04,
        4.57577892e-02,  1.42234024e-02,  1.36258528e-02, -8.27547386e-02,
        2.42147525e-03,  7.76941190e-03,  2.37005181e-03,  3.41797364e-03,
       -3.80556695e-02, -3.71713229e-02,  2.90714615e-06, -3.15324031e-02,
        1.35303633e-02,  8.62694718e-03, -1.37330657e-02,  5.94594553e-02,
       -1.63851865e-02, -6.71755429e-03, -5.46265952e-03, -5.77758113e-03,
       -4.73499484e-02,  1.81690883e-02, -3.09005603e-02,  4.78188172e-02,
        5.56063056e-02, -4.02357392e-02, -8.76401737e-03,  4.43951339e-02,
       -4.96436208e-02,  

In [ ]:
import faiss

In [ ]:
d = sentence_embeddings.shape[1]
d

768

In [ ]:
faiss.Index

faiss.swigfaiss.Index

In [ ]:
index = faiss.IndexFlatL2(d)

In [ ]:
index.is_trained

True

In [ ]:
index.add(sentence_embeddings)

In [ ]:
index.ntotal

500000

In [ ]:
k = 10
xq = model.encode(["الولايات المتحدة"])

In [ ]:
%%time
D, I = index.search(xq, k)
print(I)

[[242796 483829 151213  45499 332406 448423 292629 220081 357742 497713]]
CPU times: user 531 ms, sys: 5 µs, total: 531 ms
Wall time: 739 ms


In [ ]:
[f'{i}: {sentences[i]}' for i in I[0]]

['242796:                                                                                                                                                                                                                               لغة ايبيرية                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          تصنيف أيزو',
 '483829: إيان كاري هو ودي جيه أمريكي ولد في سبتمبر في بالتيمور في الولايات المتحدة',
 '151213:                        لاهندا                                 

In [ ]:
nlist = 100
quantizer = faiss.IndexFlatL2(d)
index = faiss.IndexIVFFlat(quantizer, d, nlist)

In [ ]:
index.is_trained

False

In [ ]:
index.train(sentence_embeddings)
index.is_trained

True

In [ ]:
index.add(sentence_embeddings)
index.ntotal

500000

In [ ]:
%%time
D, I = index.search(xq, k)
print(I)

[[483829 332406 448423 292629 220081 331482 155072 201987 204767 416352]]
CPU times: user 6 ms, sys: 3 µs, total: 6 ms
Wall time: 5.63 ms


In [ ]:
[f'{i}: {sentences[i]}' for i in I[0]]

['483829: إيان كاري هو ودي جيه أمريكي ولد في سبتمبر في بالتيمور في الولايات المتحدة',
 '332406: يح الاسم العلمي  جنس حشرات من العث وتنتمي إلى فصيلة الليليات الأنواع                                                      المراجع          تصنيف ليليات',
 '448423: حسن أباد هي     تقع في فارس في إيران انظر أيضا قائمة مدن إيران مراجع تصنيف أماكن مأهولة في مقاطعة فيروز آباد',
 '292629: إرنست ديفيد هو ألماني ولد في مارس وتوفي في معرض صور              مراجع تصنيف مواليد تصنيف وفيات',
 '220081: وب جنس حشرات عثية من فصيلة الزخلوبيات أنواع مختارة             زخلوب العفص                              المراجع    تصنيف زخلوبيات',
 '331482: جنس فطريات من فصيلة الدشيات أنواعه نحو الأنواع                                           المراجع تصنيف دشيات',
 '155072: جنس دويبات مائية من القشريات وفصيلة الدوبريات أنواعه كتالي                                                         المراجع تصنيف أجناس متساويات الأقدام',
 '201987: كيراموتي هي مدينة في كافالا في مقاطعة فوريا إلادا في اليونان معرض صور              م

In [ ]:
index = faiss.index_factory(d, "IVF100,Flat")
index.nprobe = 10
index.is_trained

False

In [ ]:
index.train(sentence_embeddings)
index.is_trained

True

In [ ]:
index.add(sentence_embeddings)
index.ntotal

500000

In [ ]:
%%time
D, I = index.search(xq, k)
print(I)

[[242796 483829 151213 332406 448423 292629 220081 497713 168194 331482]]
CPU times: user 41.2 ms, sys: 1 µs, total: 41.2 ms
Wall time: 41.1 ms


In [ ]:
[f'{i}: {sentences[i]}' for i in I[0]]

['242796:                                                                                                                                                                                                                               لغة ايبيرية                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          تصنيف أيزو',
 '483829: إيان كاري هو ودي جيه أمريكي ولد في سبتمبر في بالتيمور في الولايات المتحدة',
 '151213:                        لاهندا                                 

In [ ]:
index = faiss.index_factory(d, "HNSW3,Flat")
index.is_trained

True

In [ ]:
index.add(sentence_embeddings)
index.ntotal

500000

In [ ]:
%%time
D, I = index.search(xq, k)
print(I)

[[117364 148618  21507 495796 409244 477534 457395 389428 131214 114478]]
CPU times: user 2.69 ms, sys: 997 µs, total: 3.69 ms
Wall time: 5.09 ms


In [ ]:
[f'{i}: {sentences[i]}' for i in I[0]]

['117364: ريتشارد وارتون هو ممثل أمريكي ولد في أعمال أفلام المختلين السبعة العالم المظلم مراجع وصلات خارجية تصنيف ممثلو أفلام أمريكيون تصنيف ممثلو تلفزيون أمريكيون تصنيف ممثلو مسرح أمريكيون تصنيف مواليد',
 '148618: روي تومسون هو فلاح وسياسي بريطاني ولد في في انتخب وقد انضم خلال للكتلة البرلمانية الحزب الديمقراطي الاتحادي مراجع تصنيف فلاحون من أيرلندا الشمالية تصنيف مواليد',
 '21507: ريتشارد ألبرت هو نحات أمريكي ولد في أبريل في في الولايات المتحدة مراجع وصلات خارجية تصنيف فنانون أدائيون أمريكيون تصنيف مواليد تصنيف نحاتون ونحاتات أمريكيون',
 '495796: مات ريتش هو مجدف أمريكي ولد في أبريل مراجع وصلات خارجية تصنيف مجدفون أمريكيون تصنيف مواليد تصنيف فائزون بميداليات بطولة العالم للتجديف في الولايات المتحدة',
 '409244: آنا كيمبرلي هي لاعبة الاسكواش بريطانية ولدت في مارس في إبسوتش في المملكة المتحدة مراجع وصلات خارجية تصنيف رياضيون من إبسوتش تصنيف لاعبات اسكواش إنجليزيات تصنيف مواليد',
 '477534: ريتشارد ترافز هو ممثل أمريكي ولد في أبريل في الولايات المتحدة وتوفي في يوليو مراجع وصلات خارجية تصن

In [ ]:
from sentence_transformers import SentenceTransformer, util
import numpy as np
import torch


In [ ]:
%%time
def semantic_search(query, top_k=3):

    query_embedding = model.encode(query, convert_to_tensor=True)


    query_embedding = query_embedding.cuda()
    sentence_embeddings_gpu = torch.tensor(sentence_embeddings).cuda()

    cosine_scores = util.pytorch_cos_sim(query_embedding, sentence_embeddings_gpu)[0]


    top_results = np.argpartition(-cosine_scores.cpu().numpy(), range(top_k))[:top_k]
    print(f"Query: {query}\nTop {top_k} most similar documents:")
    for idx in top_results:
        print(f"Document: {sentences[idx]}, Score: {cosine_scores[idx]:.4f}")

semantic_search("إيران")
