<a href="https://colab.research.google.com/github/SARA3SAEED/LLM-2/blob/main/16_small_data_lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install datasets nltk
from datasets import load_dataset
import nltk
nltk.download('punkt')
from nltk.tokenize import sent_tokenize



text_dataset =  load_dataset("SaiedAlshahrani/Arabic_Wikipedia_20230101_bots")

text = text_dataset['train']['text']

sentences = []
for item in text:
    sentences.extend(sent_tokenize(item))

documents = sentences[:1000000]
print(len(documents))
print(documents[0])

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 547.8/547.8 kB 12.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 5.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 316.1/316.1 kB 8.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.9/39.9 MB 15.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 3.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 9.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 8.1 MB/s eta 0:00:00
  Attempting uninstall: requests
    Found existing installation: requests 2.31.0
    Uninstalling requests-2.31.0:
      Successfully uninstalled requests-2.31.0
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 14.0.2
    Uninstalling pyarrow-14.0.2:
      Successfully uninstalled pyarrow-14.0.2
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2024.6.1
    Uninstalling fsspec-2024.6.1:
      

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


Generating train split:   0%|          | 0/1087947 [00:00<?, ? examples/s]

1000000
text


In [ ]:
len(set(documents))
sentences = [word for word in list(set(documents)) if type(word) is str]

In [ ]:
len(sentences)

980245

In [ ]:
import numpy as np
!pip install faiss-gpu #cpu

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.5/85.5 MB 16.5 MB/s eta 0:00:00


In [ ]:
!pip install -U sentence-transformers

  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinu

In [ ]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer("sentence-transformers/all-mpnet-base-v2")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
%%time
sentences_short = sentences[:5000]
sentence_embeddings_short = model.encode(sentences_short)
sentence_embeddings_short.shape

CPU times: user 1min 48s, sys: 276 ms, total: 1min 49s
Wall time: 1min 45s


(5000, 768)

In [ ]:
sentences_short[1]

'لوسيوس سيث هانتينغتون هو سياسي كندي ولد في مايو في كونتون في كندا وتوفي في مايو في نيويورك في الولايات المتحدة نشط حزبيا في الحزب الليبرالي الكندي وقد انتخب عضو مجلس العموم الكندي مراجع وصلات خارجية تصنيف أعضاء مجلس العموم الكندي من كيبك تصنيف أعضاء مجلس الملكة الخاص بكندا تصنيف كنديون من أصل أمريكي تصنيف كوبيكيون إنجليزيو لغة الأم تصنيف مواليد تصنيف نواب الحزب الليبرالي الكندي تصنيف وفيات تصنيف مدراء مكاتب بريد عامة من كندا'

In [ ]:
sentence_embeddings_short[1]

array([ 2.84480373e-03,  6.37562871e-02, -1.49196787e-02,  1.78768635e-02,
       -6.41109273e-02,  1.76022276e-02,  9.41246152e-02,  2.01576799e-02,
        4.83843721e-02,  1.26847802e-02,  4.31374796e-02, -9.71579738e-03,
        1.53599121e-02, -3.81251834e-02, -2.76494911e-03,  5.10613434e-02,
       -1.38385966e-03,  2.57797632e-03, -8.05526040e-03,  4.00648303e-02,
       -4.84102927e-02,  5.06707542e-02,  2.50684656e-03,  1.98775660e-02,
        3.69473323e-02,  8.25105794e-03,  2.26798467e-02, -8.59116837e-02,
        1.33862235e-02,  2.38885470e-02,  1.47687634e-02,  3.54569871e-03,
       -4.29121479e-02, -4.36425619e-02,  2.74979925e-06, -3.11201289e-02,
        9.87570453e-03,  1.15290405e-02, -7.02401390e-03,  5.75824939e-02,
       -3.27657885e-03, -1.52904056e-02, -9.66620538e-03, -8.62626452e-03,
       -4.23074402e-02,  2.29321290e-02, -2.74917819e-02,  4.89847735e-02,
        4.54289243e-02, -3.87595110e-02, -2.38133711e-03,  2.29048915e-02,
       -5.46244122e-02,  

In [ ]:
import faiss

In [ ]:
d = sentence_embeddings_short.shape[1]
d

768

In [ ]:
faiss.Index

faiss.swigfaiss.Index

In [ ]:
index = faiss.IndexFlatL2(d)

In [ ]:
index.is_trained

True

In [ ]:
index.add(sentence_embeddings_short)

In [ ]:
index.ntotal

5000

In [ ]:
k = 10
xq = model.encode(["إيران"])

In [ ]:
%%time
D, I = index.search(xq, k)
print(I)

[[2314 1236  727  103 1437 2696 1608 3362 3135 3835]]
CPU times: user 5.86 ms, sys: 966 µs, total: 6.83 ms
Wall time: 5.98 ms


In [ ]:
[f'{i}: {sentences_short[i]}' for i in I[0]]

['2314: زحمت أباد هي منطقة سكنية تقع في إيران في    انظر أيضا قائمة مدن إيران مراجع تصنيف أماكن مأهولة في مقاطعة عنبر أباد',
 '1236: غران فيا هي محطة مترو أنفاق في مدريد في إسبانيا تقع على الخط رقم  مراجع تصنيف تأسيسات سنة في إسبانيا تصنيف محطات السكك الحديدية افتتحت في تصنيف محطات مترو مدريد',
 '727: شموت إحدى القرى اللبنانية في قضاء جبيل المسافة من بيروت كلم الارتفاع عن سطح البحر المراجع معلومات عن القرية في موقع لوكاليبان تصنيف قرى لبنان',
 '103: روبرت ليندمان بالإنجليزية   بالألمانية   هو عازف كلارينيت ألماني وأمريكي ولد في يناير وتوفي في مراجع تصنيف مهاجرون ألمان إلى الولايات المتحدة تصنيف مواليد تصنيف وفيات',
 '1437: كهلان هي قرية في مقاطعة مراغة إيران عدد سكان هذه القرية هو في سنة مراجع تصنيف أماكن مأهولة في مقاطعة مراغة تصنيف بلدات وقرى في مقاطعة مراغة',
 '2696: بطباط أفغاني الاسم العلمي   هو من النباتات يتبع البطباط من ال البطباطية انظر أيضا البطباط قائمة أنواع البطباط مراجع بطباط أفغاني بطباط أفغاني',
 '1608: بردز هي قرية في مقاطعة أصفهان إيران في تعداد عام لوحظ وجودها ولكن ل

In [ ]:
nlist = 100
quantizer = faiss.IndexFlatL2(d)
index = faiss.IndexIVFFlat(quantizer, d, nlist)

In [ ]:
index.is_trained

False

In [ ]:
index.train(sentence_embeddings_short)
index.is_trained

True

In [ ]:
index.add(sentence_embeddings_short)
index.ntotal

5000

In [ ]:
%%time
D, I = index.search(xq, k)
print(I)

[[2314 1236  727 1437 1608 3835 1361 4593  361 2905]]
CPU times: user 2.19 ms, sys: 13 µs, total: 2.2 ms
Wall time: 2.21 ms


In [ ]:
index = faiss.index_factory(d, "IVF100,Flat")
index.nprobe = 10
index.is_trained

False

In [ ]:
index.train(sentence_embeddings_short)
index.is_trained

True

In [ ]:
index.add(sentence_embeddings_short)
index.ntotal

5000

In [ ]:
%%time
D, I = index.search(xq, k)
print(I)

[[2314 1236  727  103 1437 2696 1608 3362 3135 3835]]
CPU times: user 1.84 ms, sys: 0 ns, total: 1.84 ms
Wall time: 1.85 ms


In [ ]:
index = faiss.index_factory(d, "HNSW3,Flat")
index.is_trained

True

In [ ]:
index.add(sentence_embeddings_short)
index.ntotal

5000

In [ ]:
%%time
D, I = index.search(xq, k)
print(I)

[[4950 1466 3944 1672 4009 2791 4319 4083 2818 4889]]
CPU times: user 1.29 ms, sys: 20 µs, total: 1.31 ms
Wall time: 5.78 ms


In [ ]:
from sentence_transformers import SentenceTransformer, util
import torch
import numpy as np

In [ ]:
%%time
def semantic_search(query, top_k=3):
    query_embedding = model.encode(query, convert_to_tensor=True)
    query_embedding = query_embedding.cuda()
    sentence_embeddings_short_gpu = torch.tensor(sentence_embeddings_short).cuda()
    cosine_scores = util.pytorch_cos_sim(query_embedding, sentence_embeddings_short_gpu)[0]
    top_results = np.argpartition(-cosine_scores.cpu().numpy(), range(top_k))[:top_k]
    print(f"Query: {query}\nTop {top_k} most similar documents:")
    for idx in top_results:
        print(f"Document: {sentences_short[idx]}, Score: {cosine_scores[idx]:.4f}")
semantic_search("إيران")

Query: إيران
Top 3 most similar documents:
Document: زحمت أباد هي منطقة سكنية تقع في إيران في    انظر أيضا قائمة مدن إيران مراجع تصنيف أماكن مأهولة في مقاطعة عنبر أباد, Score: 0.4568
Document: غران فيا هي محطة مترو أنفاق في مدريد في إسبانيا تقع على الخط رقم  مراجع تصنيف تأسيسات سنة في إسبانيا تصنيف محطات السكك الحديدية افتتحت في تصنيف محطات مترو مدريد, Score: 0.4193
Document: شموت إحدى القرى اللبنانية في قضاء جبيل المسافة من بيروت كلم الارتفاع عن سطح البحر المراجع معلومات عن القرية في موقع لوكاليبان تصنيف قرى لبنان, Score: 0.4167
CPU times: user 32.6 ms, sys: 14.8 ms, total: 47.5 ms
Wall time: 58.9 ms
